import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class RateDetails {
  final String vehicleType; // 'car' or 'motorcycle'
  final double baseRatePerHour;
  final double timeMultiplier;
  final double occupancyMultiplier;
  final double finalHourlyRate;
  final double totalCost;
  final String demandPeriodLabel;
  final String surgeReason;
  final String aiTip;

  RateDetails({
    required this.vehicleType,
    required this.baseRatePerHour,
    required this.timeMultiplier,
    required this.occupancyMultiplier,
    required this.finalHourlyRate,
    required this.totalCost,
    required this.demandPeriodLabel,
    required this.surgeReason,
    required this.aiTip,
  });

  Map<String, dynamic> toJson() => {
    'vehicleType': vehicleType,
    'baseRatePerHour': baseRatePerHour,
    'timeMultiplier': timeMultiplier,
    'occupancyMultiplier': occupancyMultiplier,
    'finalHourlyRate': finalHourlyRate,
    'totalCost': totalCost,
    'demandPeriodLabel': demandPeriodLabel,
    'surgeReason': surgeReason,
    'aiTip': aiTip,
  };
}

class RateEngineService {
  static final RateEngineService _instance = RateEngineService._internal();
  factory RateEngineService() => _instance;
  RateEngineService._internal();

  /// Calculates dynamic parking rate based on vehicle type, time of day, and occupancy
  Future<RateDetails> calculateDynamicRate({
    required String vehicleType, // 'car' or 'motorcycle' / 'bike'
    required double durationHours,
    DateTime? requestTime,
    double? customOccupancyRate,
  }) async {
    final now = requestTime ?? DateTime.now();
    
    // 1. Vehicle Type Differentiation
    final bool isCar = vehicleType.toLowerCase() == 'car';
    final double baseRate = isCar ? 40.0 : 20.0;

    // 2. Time-of-Day Demand Multiplier
    double timeMultiplier = 1.0;
    String demandLabel = "STANDARD CAMPUS";

    final hour = now.hour;
    if (hour >= 9 && hour < 12) {
      // Peak morning rush (9 AM - 12 PM)
      timeMultiplier = 1.25;
      demandLabel = "PEAK MORNING RUSH (+25%)";
    } else if (hour >= 17 || hour < 7) {
      // Off-peak evening / night discount (5 PM onwards or early morning)
      timeMultiplier = 0.75;
      demandLabel = "OFF-PEAK DISCOUNT (-25%)";
    } else {
      // Standard daytime (12 PM - 5 PM)
      timeMultiplier = 1.0;
      demandLabel = "STANDARD HOURS";
    }

    // 3. Occupancy Surge Multiplier
    double occupancyRate = customOccupancyRate ?? 0.0;
    if (customOccupancyRate == null) {
      try {
        final snapshot = await FirebaseFirestore.instance.collection('parkingSpots').get();
        if (snapshot.docs.isNotEmpty) {
          int occupied = snapshot.docs.where((doc) => doc['status'] == 'booked').length;
          occupancyRate = occupied / snapshot.docs.length;
        }
      } catch (e) {
        debugPrint("Error fetching occupancy for rate engine: $e");
      }
    }

    double occupancyMultiplier = 1.0;
    if (occupancyRate >= 0.80) {
      occupancyMultiplier = 1.20; // +20% surge if over 80% full
    }

    // 4. Combined Rate Calculation
    final double finalHourlyRate = (baseRate * timeMultiplier * occupancyMultiplier).roundToDouble();
    final double totalCost = (finalHourlyRate * durationHours).roundToDouble();

    // 5. GenAI Prompt Engineering Rationale & Savings Tip
    final aiInsights = _generateAIPricingInsights(
      isCar: isCar,
      baseRate: baseRate,
      timeMultiplier: timeMultiplier,
      occupancyRate: occupancyRate,
      demandLabel: demandLabel,
      finalHourlyRate: finalHourlyRate,
      durationHours: durationHours,
      now: now,
    );

    return RateDetails(
      vehicleType: isCar ? 'Car' : 'Motorcycle',
      baseRatePerHour: baseRate,
      timeMultiplier: timeMultiplier,
      occupancyMultiplier: occupancyMultiplier,
      finalHourlyRate: finalHourlyRate,
      totalCost: totalCost,
      demandPeriodLabel: demandLabel,
      surgeReason: aiInsights['reason']!,
      aiTip: aiInsights['tip']!,
    );
  }

  /// GenAI Prompt Engineering Logic & Rationale Generator
  Map<String, String> _generateAIPricingInsights({
    required bool isCar,
    required double baseRate,
    required double timeMultiplier,
    required double occupancyRate,
    required String demandLabel,
    required double finalHourlyRate,
    required double durationHours,
    required DateTime now,
  }) {
    // Chain-of-Thought rationale steps generated by AI engine logic
    String reason;
    String tip;

    if (timeMultiplier > 1.0) {
      reason = "High campus rush between 9 AM - 12 PM applied a 25% morning surge factor.";
      tip = "💡 AI Tip: Parking after 12:00 PM saves 20% on hourly parking rates.";
    } else if (timeMultiplier < 1.0) {
      reason = "Off-peak evening discount active (-25% savings). Base rate reduced from ₹${baseRate.toInt()} to ₹${finalHourlyRate.toInt()}/hr.";
      tip = "🎉 AI Tip: You are benefiting from off-peak evening rates!";
    } else if (occupancyRate >= 0.80) {
      reason = "Campus parking is over 80% full! High occupancy surge (+20%) applied to encourage turnover.";
      tip = "⚡ AI Tip: Reserve now before remaining spots fill up.";
    } else {
      reason = "Standard baseline rate applied for ${isCar ? '4-Wheeler' : '2-Wheeler'} vehicle.";
      tip = "👍 AI Tip: Park during evening hours (after 5 PM) to unlock 25% off-peak discounts.";
    }

    return {
      'reason': reason,
      'tip': tip,
    };
  }

  /// Formatted Prompt Engineering Template for documentation / LLM extension
  static String getPromptEngineeringTemplate({
    required String vehicleType,
    required int hour,
    required double occupancyPercent,
  }) {
    return '''
[SYSTEM PROMPT]
You are "PARK30 Dynamic Pricing Engine", an AI microservice for Marwadi University Smart Parking.
Calculate dynamic hourly rate using Chain-of-Thought reasoning.

[INPUT CONTEXT]
- Vehicle Type: $vehicleType (Car Base: ₹40/hr, Bike Base: ₹20/hr)
- Current Time: $hour:00
- Campus Occupancy: ${occupancyPercent.toStringAsFixed(1)}%

[FEW-SHOT EXAMPLES]
Example 1:
Input: Vehicle=Car, Time=10 AM, Occupancy=60%
Reasoning:
1. Base Rate = ₹40/hr.
2. Time 10 AM falls in Morning Rush (9-12 PM) -> Multiplier 1.25x.
3. Occupancy 60% < 80% -> Multiplier 1.0x.
4. Rate = 40 * 1.25 = ₹50/hr.
Output JSON: {"finalRate": 50, "surgeLabel": "Peak Morning Rush", "tip": "Park after 12 PM for baseline rates."}

[RESPONSE FORMAT]
Strictly output JSON with keys: finalRate, surgeLabel, tip, rationale.
''';
  }
}
